export const TEST_MODE_CONFIG = {
  TEST_MODE_ENABLED: true,
  GUEST_MODE_ENABLED: true,
  GUEST_TEST_CREDITS: 100,
  GUEST_SESSION_EXPIRY_HOURS: 24,
  VANTA_GENERATION_MODE: "mock" as "mock" | "hybrid" | "live",
  MOCK_FAILURE_RATE: 0.0,
  GUEST_CONCURRENT_LIMIT: 1,
  GUEST_MAX_UPLOAD_SIZE_MB: 50,
};
